using UnityEngine;
using System.Collections;
using UnityEditor;
using System.IO;
using System;
using Unity.VisualScripting.YamlDotNet.Core.Tokens;

public class GenerateTagsFile : Editor 
{
    /// <summary>
    /// A ideia desse método é criar um arquivo Tags.cs onde vai ter todas tags do editor de forma automática.
    /// Veja os comentários nesse PR aqui: https://github.com/daniro-san/shooting-bad/pull/1
    /// </summary>
    [MenuItem("Ayuda me tesoro/Generate Tags File")]
    private static void NewMenuOption() 
    {
        string filePath = Application.dataPath + "/Scripts/Helpers/Tags.cs";

        try 
        {
            using (StreamWriter writer = new StreamWriter(filePath)) 
            {
                writer.WriteLine("// THIS WAS AUTO-GENERATED BY 'Ayuda me tesoro/Generate Tags File' SCRIPT. DO NOT CHANGE THIS FILE!");
                writer.WriteLine("public static class Tags {");
                string[] allTags = UnityEditorInternal.InternalEditorUtility.tags;

                foreach (string tag in allTags) {
                    writer.WriteLine("public static readonly string " + tag + ";");
                }

                writer.WriteLine("}");
            }

            Debug.Log("[TESOURINHO][GenerateTagsFile] Success! Tags have been written to " + filePath);
        } 
        catch (Exception e) 
        {
            Debug.LogError("[TESOURINHO][GenerateTagsFile]: Error! " + e.Message);
        }
    }
}
