// THIS WAS AUTO-GENERATED BY 'Ayuda me tesoro/Generate Tags File' SCRIPT. DO NOT CHANGE THIS FILE!
public static class Tags {
public static readonly string Untagged;
public static readonly string Respawn;
public static readonly string Finish;
public static readonly string EditorOnly;
public static readonly string MainCamera;
public static readonly string Player;
public static readonly string GameController;
public static readonly string Enemy;
public static readonly string Bullet;
}
